export const Constant = {
  device: 'budyclub.com/SETUP_DEVICE',
  micId: 'budyclub.com/MIC_ID_SETUP',
  producer: 'budyclub.com/PRODUCER_SETUP',
  close_producer: 'budyclub.com/CLOSE_PRODUCER',
  consumer: 'budyclub.com/CONSUMER_SETUP',
  close_consumer: 'budyclub.com/CLOSE_CONSUMER',
  roomId: 'budyclub.com/SET_ROOM_ID',
  micStream: 'budyclub.com/SET_MIC_STREAM',
  mic: 'budyclub.com/SET_MIC',
  recvTransport: 'budyclub.com/RECV_TRANSPORT',
  sendTransport: 'budyclub.com/SEND_TRANSPORT',
  user_id: 'budyclub.com/USER_ID',
  peer_id: 'budyclub.com/PEER_ID',
  requesting_to_speak: 'budyclub.com/PPL_REQ_TO_SPEAK',
  room_data: 'budyclub.com/ROOM_DATA',
  mute_unmute: 'budyclub.com/MUTE_UNMUTE_MIC',
  connectionstatechange: 'budyclub.com/CONNECTION_STATE_CHANGE',
  unmountRoomScreen: 'budyclub.com/UNMOUNT_ROOM_SCREEN',
  access_token: 'budyclub.com/USER_ACCESS_TOKEN',
  deviceToken: 'budyclub.com/DEVICE_ID_FCM',
  set_requests: 'budyclub.com/REQUESTS_TO_SPEAK',
  rm_requests: 'budyclub.com/REMOVE_REQUESTS',
  isEarPhonePlugged: 'budyclub.com/IS_EAR_PHONE_PLUGGED',
  isConnected: 'budyclub.com/IS_CONNECTED',
  appState: 'budyclub.com/APP_STATE',
  audioMode: 'budyclub.com/AUDIO_MODE',
  chatMessages: 'budyclub.com/CHAT_MESSAGES',
  updateMessages: 'budyclub.com/UPDATE_MESSAGES',
  peerRequest: 'budyclub.com/PEER_REQUEST',
  peerRequestData: 'budyclub.com/PEER_REQUEST_DATA',
  openRequestModal: 'budyclub.com/OPEN_REQUEST_MODAL',
  closeRequestModal: 'budyclub.com/CLOSE_REQUEST_MODAL',
  speakingChange: 'budyclub.com/SPEAKING_CHANGE',
  openUpdateRoomTitleModal:
    'budyclub.com/OPEN_UPDATE_ROOM_TITLE_DESCRIPTION_MODAL',
  closeUpdateRoomTitleModal:
    'budyclub.com/CLOSE_UPDATE_ROOM_TITLE_DESCRIPTION_MODAL',
};
